### ISSUE TITLE
Questions regarding potential risks

### ISSUE THREAD

**Issue by CENGOiSM** [gdoor-org/gdoor#30]
Assuming one has a non-faulty PCB and ESP32, how likely is it to damage GIRA components?
Naturally, reverse-engineering both the software and hardware design introduces potential incompatibilities and errors.
However, how significant could the impact be on other participants, the bus, or the TKS system in general?

I live in a rented apartment and would love to install gdoor, but I'm currently weighing the associated risks.

**Comment by DaSchaef** [comment]
This is a tricky question.

So in principle the bus adapter should not pose any risk, yet there are caveats as in reality it is hard to catch all bus installations:

- The Gira bus itself is short circuit proof.

For the GDoor adapter:
- The GDoor bus adapter uses a diode bridge, so  bus polarity does not matter.
- The interfaces to the bus are AC coupled, so no risk to send a wrong voltage level to the bus.
- Yet it has a certain RX and TX capacitance, by principle, as any other Gira device. 
 These should be negligible.
- If your ESP would go wild an send all the time, it could theoretically disturb the bus for all, but not damage it.

There is one connection which may be tricky: The power supply of the GDoor bus adapter:
The bus adapter connects the Ground of the power supply to the ground of the bus.
This should pose no problem ("connect 0V to 0V"), but as a developer we can not know how your Gira installation is done.
Even Gira itself warns about this, as this also may happen in regular installations with their own devices.
e.g. https://partner.gira.de/service/faq/antwort.html?id=1254
Even here, I can not think about a situation were you damage something.

Paranoia mode:
1. Use a isolating 5V supply e.g. MeanWell HDR-15-5, or a USB power supply without earth connection (most of them).
Do not use a computer or similar to power the GDoor adapter.
2. Do not connect to the USB with your computer while the GDoor adapter is connected to the Gira bus.
Only use Wifi.

Please remember this is an open source project with no guarantee. If in doubt you may want to contact a friend/colleague or similar with electrical or electronic background and ask for help on your specific installation.
