### ISSUE TITLE
Solder description

### ISSUE THREAD

**Issue by mikburnz** [gdoor-org/gdoor#32]
A more detailed description is necessary. Which rows of the PCB are being soldered? The photo shows 3 out of 4 rows. Is that sufficient? Which rows of the 4 are to solder?
![IMG_5507](https://github.com/user-attachments/assets/061736d6-c143-4149-876b-ff0a75c70417)

**Comment by DaSchaef** [comment]
Best is to solder just all,
if you want to save solder time, the minimum needed pins are marked on the back of the PCB.

![grafik](https://github.com/user-attachments/assets/1378a78c-f480-4394-b8d0-f484ab4c652c)
