### ISSUE TITLE
Documentation shell command

### ISSUE THREAD

**Issue by mikburnz** [gdoor-org/gdoor#34]
Is the documentation correct? 

shell command in configuration.yaml is different than in the action: call service.
gdoor_open_door vs. open_house_door

![shell command](https://github.com/user-attachments/assets/85610ffc-ea40-44a9-a827-27861a6ba516)

**Comment by DaSchaef** [comment]
I'm no HA user, I can't check/comment. But I can correct it, if it is wrong.
(I would recommend the Wifi/MQTT connection)

**Comment by jschroeter** [comment]
Thanks for the hint, it was indeed incorrect. I fixed it.
