### ISSUE TITLE
Feedback needed! (to progress on audio)

### ISSUE THREAD

**Issue by DaSchaef** [gdoor-org/gdoor#36]
Dear all,
while developing a future GDoor version with audio support,
I would need the support of people currently using the GDoor adapter:

Could you please check, if you GDoor works reliable with the following settings:

**WebInterface**
RX Input = v3.1 (IO21)

If this is working reliable, this would free up IO22 and IO26 for audio support.

**Comment by github-k8n** [comment]
Works fine for me ..

**Comment by jschroeter** [comment]
Also works for me, didn’t notice any issues.
