### ISSUE TITLE
Output is invalid JSON

### ISSUE THREAD

**Issue by jschroeter** [gdoor-org/gdoor#4]
e.g. validate the output with https://jsonlint.com/:
- trailing commas are not allowed
- hex values are not allowed

**Comment by jschroeter** [comment]
I quickly tried using ArduinoJson in https://github.com/gdoor-org/gdoor/tree/4-output-is-invalid-json but need some help/more time. Also not sure if this is needed knowing that @ravenst0ne is working on something similar already?

**Comment by DaSchaef** [comment]
ArduinoJson is a pretty big library. But I would add it, we also want to receive json, and with ArduinoJson we can avoid complicated string parsing.

**Comment by DaSchaef** [comment]
Closed in #6
