### ISSUE TITLE
Question from JLCPCB about orientation of Connector

### ISSUE THREAD

**Issue by Shoomaan** [gdoor-org/gdoor#42]
Could you please help me with the following question concerning my order. 

Dear customer,

Well got your order with many thanks.

Sorry to bother you, but there is one thing that we want to confirm with you about your PCBA order SMT024112360326_Y48812901A  before proceeding.

Are the orientation of THT parts on 3D render correct?

![IMG_7738](https://github.com/user-attachments/assets/f5b15b8a-62bd-4eef-a59b-7bc87fc67af3)

**Comment by DaSchaef** [comment]
Yes orientation is correct
