### ISSUE TITLE
Add high-level props to JSON output

### ISSUE THREAD

**Issue by jschroeter** [gdoor-org/gdoor#5]
To allow comfortable automations/triggers in Smart Home platforms like Home Assistant.

Suggestion for new fields:
- action: doorBell / floorBell / openDoor / ...
- param: which button was pressed
- deviceType: doorStation / indoorStation / controller
- source
- destination

**Comment by DaSchaef** [comment]
We can re-use (and migrate to class based C++) from the STM32 code:
https://github.com/gdoor-org/gdoor/blob/a9e28f83e366b4aa6abce5f1029c4be776966766/firmware/stm32-ugly/Core/Inc/gdoor_protocol.h (and corresponding C file)

**Comment by DaSchaef** [comment]
Can you test #6 ?
I expect that it will **not** work on first try, as it is a dry run implementation,
with significant refactoring in the RX logic.

Additionally this should also fix #4 without the big ArduinoJSON library dependency.

**Comment by DaSchaef** [comment]
Closed in #6
