### ISSUE TITLE
Last action gets repeated?

### ISSUE THREAD

**Issue by jschroeter** [gdoor-org/gdoor#8]
I think there might be a bug in the firmware: apparently the last received action is repeated every now an then. In the screenshot there is a log of the actions received by Gdoor (note the increasing event_id). E.g. there are actions received during night time where there was clearly no user interaction. Maybe there are (yet unknown) things going on on the bus and due to a bug the last received action is detected again?
Unfortunately I don't have a debug mode log recorded yet - I'll try to record one asap.

<img width="648" alt="gdoor-log" src="https://github.com/gdoor-org/gdoor/assets/487046/ccecac9d-957b-4d9f-a8d2-20d779ea06f2">

**Comment by DaSchaef** [comment]
Reading the code,
there may be a bug in https://github.com/gdoor-org/gdoor/blob/main/firmware/esp32/gdoor/src/gdoor_data.cpp#L56

I'll try to commit a easy fast fix

**Comment by DaSchaef** [comment]
Please check :)

**Comment by jschroeter** [comment]
Looks good, thanks!
Do you know what triggered these?
